#pragma once

#include <ntddk.h>

#include "utils.h"

#define TYPES

typedef unsigned long BOOL;

// #enddef TYPES

#define IOCTL_CODES

/*
 * @brief IOCTL code for testing the hypervisor
 */
#define IOCTL_HYROAPI_TEST \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_EPT_ADD \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_EPT_REMOVE \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_EPT_ENABLE \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_EPT_DISABLE \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_EPT_MODIFY \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GENERAL_GET_PHYSICAL_ADDRESS \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GENERAL_ALLOC_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GENERAL_FREE_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GENERAL_COPY_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GENERAL_EXECUTE_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GUEST_GENERAL_COPY_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HYROAPI_GUEST_GENERAL_EXECUTE_NONPAGED_BUFFER \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80c, METHOD_BUFFERED, FILE_ANY_ACCESS)

// #enddef

#define HYRO_CALL

/*
 * @brief Call the hypervisor
 * @return `HYRO_VMCALL_SUCCESS` if the call was successful
 */
extern UINT64 ACallHyro(UINT64 c, UINT64 p1, UINT64 p2, UINT64 p3);

// #enddef

#define HYRO_VMCALL_NUMBERS

#define HYRO_VMCALL_SUCCESS 0xd81b57669c771f7d
#define HYROCALL_SUCCESS(x) x == HYRO_VMCALL_SUCCESS ? TRUE : FALSE

#define HYRO_VMCALL_TEST 0x0

#define HYRO_VMCALL_EPT_ADDITION 0x2
#define HYRO_VMCALL_EPT_REMOVAL 0x3
#define HYRO_VMCALL_EPT_DISABLE 0x4
#define HYRO_VMCALL_EPT_ENABLE 0x5
#define HYRO_VMCALL_EPT_MODIFY 0x6

#define HYRO_VMCALL_GENERAL_GET_PHYSICAL_ADDRESS 0x7
#define HYRO_VMCALL_GENERAL_ALLOC_NONPAGED_BUFFER 0x8
#define HYRO_VMCALL_GENERAL_FREE_NONPAGED_BUFFER 0x9
#define HYRO_VMCALL_GENERAL_COPY_NONPAGED_BUFFER 0xa
#define HYRO_VMCALL_GENERAL_EXECUTE_NONPAGED_BUFFER 0xb

// #enddef

#define USER_KERNEL_MITIGATIONS